---
title: "Ch.6_Testing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(keras)
library(tensorflow)
library(tidyverse)
library(tibble)
library(readr)
```

# Check GPU
```{r}
tf$config$experimental$list_physical_devices()
### GPU is found
```
# Check if linux works in git bash

```{bash}
#nvidia-smi -l 1
# Works
```

## Listing 6.37

```{r}
# Load data
data_dir <- "jena_climate"
fname <- file.path(data_dir, "jena_climate_2009_2016.csv")
data <- read_csv(fname)
head(data)
```

```{r}
# Format data
data <- data.matrix(data[,-1])
train_data <- data[1:200000,]
mean <- apply(train_data, 2, mean)
std <- apply(train_data, 2, sd)
data <- scale(data, center = mean, scale = std)
```


```{r}
# Make generator function
generator <- function(data, lookback, delay, min_index, max_index,
                      shuffle = FALSE, batch_size = 128, step = 6) {
  if (is.null(max_index)) max_index <- nrow(data) - delay - 1
  i <- min_index + lookback
  function() {
    if (shuffle) {
      rows <- sample(c((min_index+lookback):max_index), size = batch_size)
    } else {
      if (i + batch_size >= max_index)
        i <<- min_index + lookback
      rows <- c(i:min(i+batch_size, max_index))
      i <<- i + length(rows)
    }
    samples <- array(0, dim = c(length(rows),
                                lookback / step,
                                dim(data)[[-1]]))
    targets <- array(0, dim = c(length(rows)))
    for (j in 1:length(rows)) {
      indices <- seq(rows[[j]] - lookback, rows[[j]],
                     length.out = dim(samples)[[2]])
      samples[j,,] <- data[indices,]
      targets[[j]] <- data[rows[[j]] + delay,2]
    }
    list(samples, targets)
  }
}
```


```{r}
# Prep data
lookback <- 1440
step <- 6
delay <- 144
batch_size <- 128
train_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 1,
  max_index = 200000,
  shuffle = TRUE,
  step = step,
  batch_size = batch_size
)
val_gen = generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 200001,
  max_index = 300000,
  step = step,
  batch_size = batch_size
)
test_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 300001,
  max_index = NULL,
  step = step,
  batch_size = batch_size
)
val_steps <- (300000 - 200001 - lookback) / batch_size
test_steps <- (nrow(data) - 300001 - lookback) / batch_size
```


```{r}
# Run model
model <- keras_model_sequential() %>%
  layer_flatten(input_shape = c(lookback / step, dim(data)[-1])) %>%
  layer_dense(units = 32, activation = "relu") %>%
  layer_dense(units = 1)
model %>% compile(
  optimizer = optimizer_rmsprop(),
  loss = "mae"
)
system.time({
  history <- model %>% fit(
  train_gen,
  steps_per_epoch = 500,
  epochs = 20,
  validation_data = val_gen,
  validation_steps = val_steps
)
})
```

```{r}
plot(history)
```

## Listing 3.39

```{r}
model <- keras_model_sequential() %>%
  layer_gru(units = 32,
            input_shape = list(NULL, dim(data)[[-1]]),
            recurrent_activation = "sigmoid",
            use_bias = TRUE,
            reset_after = TRUE) %>%
  layer_dense(units = 1)
model %>% compile(
  optimizer = optimizer_rmsprop(),
  loss = "mae"
)

system.time({
  history <- model %>% fit(
  train_gen,
  steps_per_epoch = 500,
  epochs = 20,
  validation_data = val_gen,
  validation_steps = val_steps
)
})
```

```{r}
plot(history)
```

## Listing 6.40

```{r}
model <- keras_model_sequential() %>%
  layer_gru(units = 32,
            dropout = 0.2,
            recurrent_dropout = 0.2,
            input_shape = list(NULL, dim(data)[[-1]]),
            recurrent_activation = "sigmoid",
            use_bias = TRUE,
            reset_after = TRUE) %>%
  layer_dense(units = 1)
model %>% compile(
  optimizer = optimizer_rmsprop(),
  loss = "mae"
)
system.time({history <- model %>% fit(
  train_gen,
  steps_per_epoch = 500,
  epochs = 40,
  validation_data = val_gen,
  validation_steps = val_steps
)
})
```

```{r}
plot(history)
```

## Listing 6.41
```{r}
model <- keras_model_sequential() %>%
  layer_gru(units = 32,
            dropout = 0.1,
            activation = "tanh",
            recurrent_dropout = 0,
            unroll = F,
            return_sequences = TRUE,
            input_shape = list(NULL, dim(data)[[-1]]),
            recurrent_activation = "sigmoid",
            use_bias = TRUE,
            reset_after = TRUE) %>%
  layer_gru(units = 64,
            dropout = 0.1,
            activation = "tanh",
            recurrent_dropout = 0,
            unroll = F,
            input_shape = list(NULL, dim(data)[[-1]]),
            recurrent_activation = "sigmoid",
            use_bias = TRUE,
            reset_after = TRUE) %>%
  layer_dense(units = 1)
model %>% compile(
  optimizer = optimizer_rmsprop(),
  loss = "mae"
)
system.time({history <- model %>% fit(
  train_gen,
  steps_per_epoch = 500,
  epochs = 40,
  validation_data = val_gen,
  validation_steps = val_steps
)
})
```

```{r}
plot(history)
```

## Listing 6.44
```{r}
## Prep data
max_features <- 10000                                              
maxlen <- 500                                                      
imdb <- dataset_imdb(num_words = max_features)
c(c(x_train, y_train), c(x_test, y_test)) %<-% imdb
x_train <- lapply(x_train, rev)                                    
x_test <- lapply(x_test, rev)
x_train <- pad_sequences(x_train, maxlen = maxlen)                 
x_test <- pad_sequences(x_test, maxlen = maxlen)
model <- keras_model_sequential() %>%
  layer_embedding(input_dim = max_features, output_dim = 128) %>%
  layer_lstm(units = 32) %>%
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("acc")
)
history <- model %>% fit(
  x_train, y_train,
  epochs = 10,
  batch_size = 128,
  validation_split = 0.2
)
```

```{r}
plot(history)
```
